### ISSUE TITLE
This version of pacopy is outdated. Please upgrade.

### ISSUE THREAD

**Issue by AhmedAbouhussein** [sigma-py/pacopy#31]
I get this error even though I download with latest pip not sure what is going on. 
Successfully installed markdown-it-py-3.0.0 mdurl-0.1.2 pacopy-0.2.7

pacopy-0.2.7 is the same one available on the main page of this repo at the moment

**Comment by nschloe** [comment]
What version are you trying to run exactly?

**Comment by nschloe** [comment]
Debugging right now...

**Comment by nschloe** [comment]
Fixed in 0.2.8.
